name: disposables
description: Simple library to manage objects needing to release its own resources.
version: 1.0.0
homepage: https://github.com/marcguilera/disposables.dart
author: marcguilera <marcguilerap@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.0.0

dev_dependencies:
  test: ^1.16.7
